// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_oWzERtlrGLT8HQt32nQY2xV5cK8566c',
    appId: '1:671561103981:web:754dd405c05e470e459d64',
    messagingSenderId: '671561103981',
    projectId: 'foodbank-1c95a',
    authDomain: 'foodbank-1c95a.firebaseapp.com',
    storageBucket: 'foodbank-1c95a.appspot.com',
    measurementId: 'G-JBTP31XYJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUP4D7f75B7C1yJWoTLuabSA39NXCiiRI',
    appId: '1:671561103981:android:d6460c09bcdc9f0a459d64',
    messagingSenderId: '671561103981',
    projectId: 'foodbank-1c95a',
    storageBucket: 'foodbank-1c95a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyRDlEcHCM64PcEnrWjdNd5IfX_hKuBk',
    appId: '1:671561103981:ios:8f69784f1f842d2f459d64',
    messagingSenderId: '671561103981',
    projectId: 'foodbank-1c95a',
    storageBucket: 'foodbank-1c95a.appspot.com',
    iosBundleId: 'com.example.foodbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyRDlEcHCM64PcEnrWjdNd5IfX_hKuBk',
    appId: '1:671561103981:ios:8f69784f1f842d2f459d64',
    messagingSenderId: '671561103981',
    projectId: 'foodbank-1c95a',
    storageBucket: 'foodbank-1c95a.appspot.com',
    iosBundleId: 'com.example.foodbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_oWzERtlrGLT8HQt32nQY2xV5cK8566c',
    appId: '1:671561103981:web:db27d99d75ab8a61459d64',
    messagingSenderId: '671561103981',
    projectId: 'foodbank-1c95a',
    authDomain: 'foodbank-1c95a.firebaseapp.com',
    storageBucket: 'foodbank-1c95a.appspot.com',
    measurementId: 'G-HWH20SKZ2F',
  );

}